---

# Pass the URL by the command line parameter
- name: Get image for test when x86_64
  get_url:
    url: "{{ image_url }}"
    dest: /var/lib/libvirt/images/

- name: Get ISO for test when s390x
  get_url:
    url: "{{ iso_url }}"
    dest: /var/lib/libvirt/images/test.iso
  when: ansible_facts["architecture"] == "s390x"
