---

- name: Install required packages
  dnf:
    name: "{{ item }}"
  with_items:
    - cockpit-machines
    - python3
    - libvirt-daemon-config-network
    - libvirt-daemon-driver-storage-iscsi
    - libvirt-daemon-driver-storage-logical
    - targetcli
    - iscsi-initiator-utils
    - python3
    - wget
    - rsync
    - dbus-tools
    - usbutils